Repository AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language, pull requests merged in 2023-05, with the labels that each got.

#314 Add video back
  lib/widgets/video/video_model.dart
  lib/widgets/video/video_view.dart
  lib/widgets/video/video_view_selector_vm.dart
  lib/widgets/video/video_view_selector_web.dart
  lib/widgets/video/video_view_vlc.dart
  lib/widgets/widget/widget_model.dart
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#345 Added onfail
  lib/datasources/gps/model.dart
Labels: bug

#359 fixed chart bug
  lib/store/store_view.dart
  lib/system.dart
  lib/widgets/chart/chart_view.dart
Labels: bug

#361 bug fix for pager build during build
  lib/widgets/framework/framework_view.dart
  lib/widgets/list/list_view.dart
  lib/widgets/pager/pager_view.dart
Labels: bug

#363 Fixed DISTINCT, added total to calc
  lib/datasources/base/model.dart
  lib/datasources/transforms/calc.dart
  lib/datasources/transforms/distinct.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug, enhancement

#365 Fix for chart axis truncation and make axis non-nullable
  lib/widgets/chart/chart_model.dart
  lib/widgets/chart/chart_view.dart
Labels: bug

#368 pie chart assignment fix
  lib/widgets/chart/axis/chart_axis_model.dart
  lib/widgets/chart/chart_view.dart
Labels: bug
