Repository AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language, pull requests merged in 2023-06, with the labels that each got.

#372 Modal View Mods
  lib/widgets/modal/modal_view.dart
Labels: enhancement

#377 Added datasource to Popover to dynamically populate PopoverMenuItems
  lib/widgets/popover/item/popover_item_model.dart
  lib/widgets/popover/popover_model.dart
  lib/widgets/popover/popover_view.dart
  lib/widgets/widget/widget_model.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: enhancement

#379 Transform elementat fix
  lib/widgets/animation/animation_child/flip/flip_card_view.dart
  lib/widgets/animation/animation_child/slide/slide_transition_view.dart
  lib/widgets/animation/animation_child/transform/transform_model.dart
  lib/widgets/animation/animation_child/transform/transform_view.dart
  lib/widgets/form/form_model.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug

#380 typeahead scrollbar fix and input hint color
  lib/widgets/form/decorated_input_model.dart
  lib/widgets/input/input_view.dart
  pubspec.yaml
Labels: bug, enhancement

#383 update packages pre 2.0
  lib/system.dart
  lib/widgets/map/map_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: enhancement

#385 button defaults
  lib/widgets/button/button_model.dart
  lib/widgets/modal/modal_model.dart
  lib/widgets/table/row/cell/table_row_cell_view.dart
Labels: bug

#387 Min max constraints
  lib/datasources/transforms/calc.dart
  lib/widgets/box/box_view.dart
  lib/widgets/camera/camera_view.dart
  lib/widgets/widget/widget_state.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug

#389 Add selectable text and fixed markdown regex
  lib/eval/text_parser.dart
  lib/widgets/span/span_model.dart
  lib/widgets/span/span_view.dart
  lib/widgets/text/text_model.dart
  lib/widgets/text/text_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug, enhancement

#397 Button fixed for fmlpad
  lib/widgets/button/button_model.dart
Labels: bug

#409 fix packaged sample application
  assets/applications/sample/templates/counter_app.xml
  assets/applications/sample/templates/main.xml
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: documentation

#410 Modified Calc's for SafeArea
  lib/system.dart
  lib/widgets/framework/framework_view.dart
  lib/widgets/treeview/tree_model.dart
  lib/widgets/widget/widget_model.dart
Labels: bug

#413 update flutter html package for linux
  lib/system.dart
  lib/widgets/html/html_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: bug

#416 chart missing datasource attribute warning and bug fix
  lib/widgets/chart/chart_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug

#425 Pager slide
  lib/widgets/pager/pager_model.dart
Labels: enhancement

#430 code editor improvements
  lib/widgets/editor/editor_view.dart
  pubspec.yaml
Labels: enhancement

#431 Add DateTime Eval Functions
  lib/eval/eval.dart
  lib/helper/color.dart
  lib/widgets/chart/chart_view.dart
Labels: enhancement

#432 Improved substring
  lib/eval/eval.dart
Labels: enhancement

#447 Mac os compatibility with google packages
  ios/Podfile.lock
  lib/system.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.yaml
Labels: enhancement
